services:
  children-budget-app:
    image: dshvechikov/children-budget:latest
    container_name: children-budget-app
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://children-budget-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_BASIC_AUTH_USERNAME: ${APP_BASIC_AUTH_USERNAME}
      APP_BASIC_AUTH_PASSWORD: ${APP_BASIC_AUTH_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - children-budget-db

  children-budget-db:
    image: postgres:16-alpine
    container_name: children-budget-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - children-budget-db-data:/var/lib/postgresql/data

volumes:
  children-budget-db-data:
